spring:

  server:
    port: 8080
  application:
    name: authentication
  datasource:
    url: jdbc:h2:file:./db/modulepurchase
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        hbm2ddl:
          auto: create
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
