spring:
  logging:
    level: org.springframework.security=DEBUG
    logging:
      level: cl.duoc.rodrcruz=DEBUG
  application:
    name: moduleusers
  datasource:
    url: jdbc:h2:file:./db/moduleuser
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8081
perfume:
  purchase:
    service:
      url: http://localhost:8080
jwt:
  secret: tu_secreto_muy_seguro_y_largo_aqui_cambialo_en_produccion_1234567890abcdef # ¡IMPORTANTE: Cambia este secreto!
  expiration:
    ms: 3600000

